name: 'drupal8'
type: 'php:7.2'

relationships:
  database: 'db:mysql'

variables:
  php:
    display_errors: Off
    display_startup_errors: Off

disk: 2048

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  '/ilr-submodule/web/sites/default/files':
      source: local
      source_path: 'files'
  '/tmp':
      source: local
      source_path: 'tmp'
  '/private':
      source: local
      source_path: 'private'
  '/.drush':
      source: local
      source_path: 'drush'
  '/drush-backups':
      source: local
      source_path: 'drush-backups'
  '/.console':
      source: local
      source_path: 'console'

# Configuration of the build of this application.
build:
  flavor: composer

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    curl -sS https://platform.sh/cli/installer | php
    set -e
    cd ilr-submodule
    npm install
    npm run build
  deploy: |
    set -e
    php ./drush/platformsh_generate_drush_yml.php
    cd ilr-submodule/web
    drush -y cache-rebuild
    drush -y updatedb
    drush -y config-import --partial

web:
  locations:
    '/':
      root: 'ilr-submodule/web'

      # How long to allow static assets from this location to be cached.
      #
      # Can be a time in seconds, or -1 for no caching. Times can be
      # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
      # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
      # 365 days).
      expires: 1d

      # Whether to forward disallowed and missing resources from this
      # location to the application.
      #
      # Can be true, false or a URI path string.
      passthru: '/index.php'

      # Deny access to static files in this location.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true

        # Deny direct access to configuration files.
        '^/sites/sites\.php$':
          scripts: false
        '^/sites/[^/]+/settings.*?\.php$':
          scripts: false

    '/sites/default/files':
      # Allow access to all files in the public files directory.
      allow: true
      expires: 5m
      passthru: '/index.php'
      root: 'ilr-submodule/web/sites/default/files'

      # Do not execute PHP scripts.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        '^/sites/default/files/(css|js)':
          expires: 2w

# The configuration of scheduled execution.
crons:
  drupal:
    # Run drush cron every hour
    spec: '0 * * * *'
    cmd: 'cd ilr-submodule/web ; drush core-cron'
