name: 'proxy'
type: 'nodejs:10'

web:
  commands:
    start: "cd ilr_proxy-submodule && npm run start"

hooks:
  build: |
    cd ilr_proxy-submodule
    npm install --production

mounts:
  run:
    source: local
    source_path: run

disk: 512
