"https://{default}/":
  type: redirect
  to: https://www.{default}/

"https://www.{default}/":
  type: upstream
  upstream: "proxy:http"
  redirects:
    expires: 300s
    paths:
      '^/(sites/(default|ilr\.cornell\.edu)/files/.*\.pdf)$':
        to: 'https://archive.{default}/download-lookup?path=$1'
        regexp: true

"https://d8.{default}/":
  type: upstream
  upstream: "drupal8:http"

"https://archive.{default}/":
  type: upstream
  upstream: proxy:http
  cache:
    enabled: false
