"https://{default}/":
  type: redirect
  to: https://www.{default}/

"https://www.{default}/":
  type: upstream
  upstream: "proxy:http"

"https://d8.{default}/":
  type: upstream
  upstream: "drupal8:http"
