db:
  type: mariadb:10.2
  disk: 2048
  configuration:
    schemas:
      - main
      - legacy
    endpoints:
      mysql:
        default_schema: main
        privileges:
          main: admin
          legacy: admin
      reporter:
        privileges:
          main: ro
          legacy: ro
      migrator:
        default_schema: legacy
        privileges:
          legacy: ro
